name = "client1-topup-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # Code ထဲက ctx.env.DB နဲ့ ကိုက်အောင်
database_name = "client1_db" # မင်းဆောက်ထားတဲ့ DB နာမည်
database_id = "c4eeb98b" # DB ရဲ့ ID
